import type { Metadata } from "next";
import React from "react";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import mainlogo from "../../public/mainlogo.png";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Header } from "@/components/Header";
import { Chatbotbtn } from "@/components/Chatbotbtn";
import { Footer } from "@/components/Footer";
import { SessionProvider } from "next-auth/react";
import { Providers } from "@/app/Providers";
import { getServerSession } from "next-auth";
import { authOptions } from "../../pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["500"] });

export const metadata: Metadata = {
  title: "LearnSpace",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  console.log(session?.user);

  return (
    <html lang="en">
      <body className={`${poppins.className} ${inter.className}`}>
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
